# Generated by Django 2.2.7 on 2019-12-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('processing', 'обработка'), ('executed', 'выполнен'), ('error', 'ошибка')], default='new', max_length=255),
        ),
    ]
