# Generated by Django 2.2.7 on 2019-11-29 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191127_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='price_items',
            field=models.ManyToManyField(to='app.PriceItem'),
        ),
    ]
